language: python

install:
  - pip install typing-extensions --upgrade  # Install typing_extensions to support TypeGuard
  - pip install -r requirements.txt  # Install dependencies

script:
  - black --check .
  - flake8 --max-line-length=150 .
  - coverage run manage.py test

after_success:
  - coveralls  # Report coverage to Coveralls

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-2  # e.g., us-west-2
#   app: django-env-1  # Your Elastic Beanstalk app name
#   env: django-env-1  # Your EB environment name
#   access_key_id: $AWS_ACCESS_KEY_ID  # Securely store in Travis CI environment variables
#   secret_access_key: $AWS_SECRET_ACCESS_KEY  # Securely store in Travis CI environment variables
#   bucket_name: elasticbeanstalk-us-west-2-717279690562
#   on:
#     branch: main  # Deploy only from the main branch
